# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20160307_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Temp Title', max_length=20),
            preserve_default=False,
        ),
    ]
